[versions]
android-buildTools = "36.1.0"
android-compileSdk = "36"
android-minSdk = "26"
android-targetSdk = "36"
androidx-activity = "1.12.3"
androidx-fragment = "1.8.9"
androidx-hilt = "1.3.0"
androidx-lifecycle = "2.10.0"
androidx-navigation = "2.9.7"
dagger-hilt = "2.59.1"
kotlin = "2.3.10"
ksp = "2.3.5"
kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.10.0"
plugin-android = "9.0.0"
plugin-kotlinter = "5.4.0"
plugin-doctor = "0.12.1"
square-okhttp = "5.3.2"
square-retrofit2 = "3.0.0"
cash-sqlDelight = "2.2.1"

[libraries]
androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-appcompat = "androidx.appcompat:appcompat:1.7.1"
androidx-composeBom = "androidx.compose:compose-bom:2026.02.01"
androidx-composeAnimation = { module = "androidx.compose.animation:animation" }
androidx-composeFoundation = { module = "androidx.compose.foundation:foundation" }
androidx-composeMaterial3 = { module = "androidx.compose.material3:material3" }
androidx-composeMaterialIconsCore = { module = "androidx.compose.material:material-icons-core" }
androidx-composeMaterialIconsExtended = { module = "androidx.compose.material:material-icons-extended" }
androidx-composeRuntime = { module = "androidx.compose.runtime:runtime" }
androidx-composeUi = { module = "androidx.compose.ui:ui" }
androidx-composeUiTestJunit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-composeUiTestManifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-composeUiTooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-composeUiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-core = "androidx.core:core-ktx:1.17.0"
androidx-datastore = "androidx.datastore:datastore-preferences-core:1.2.0"
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }
androidx-lifecycleCompiler = { module = "androidx.lifecycle:lifecycle-compiler", version.ref = "androidx-lifecycle" }
androidx-lifecycleRuntimeCompose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycleRuntimeTesting = { module = "androidx.lifecycle:lifecycle-runtime-testing", version.ref = "androidx-lifecycle" }
androidx-lifecycleViewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycleViewmodelSavedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "androidx-lifecycle" }
androidx-hiltNavigationFragment = { module = "androidx.hilt:hilt-navigation-fragment", version.ref = "androidx-hilt" }
androidx-navigation = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-navigationTesting = { module = "androidx.navigation:navigation-testing", version.ref = "androidx-navigation" }
androidx-testExtJunit = "androidx.test.ext:junit-ktx:1.3.0"
androidx-testEspressoCore = "androidx.test.espresso:espresso-core:3.7.0"
androidx-viewPager2 = "androidx.viewpager2:viewpager2:1.1.0"
dagger-hiltAndroid = { module = "com.google.dagger:hilt-android", version.ref = "dagger-hilt" }
dagger-hiltCompiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "dagger-hilt" }
dagger-hiltAndroidTesting = { module = "com.google.dagger:hilt-android-testing", version.ref = "dagger-hilt" }
google-material = "com.google.android.material:material:1.13.0"
javax-inject = "javax.inject:javax.inject:1"
junit = "junit:junit:4.13.2"
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-testJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlinx-coroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutinesAndroid = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-collectionsImmutable = "org.jetbrains.kotlinx:kotlinx-collections-immutable:0.4.0"
kotlinx-serializationCore = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinter-compose-rules = "io.nlopez.compose.rules:ktlint:0.5.6"
square-leakcanaryAndroid = "com.squareup.leakcanary:leakcanary-android:2.14"
square-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "square-okhttp" }
square-okhttpLoggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "square-okhttp" }
square-retrofit2 = { module = "com.squareup.retrofit2:retrofit", version.ref = "square-retrofit2" }
square-retrofit2ConverterSerialization = { module = "com.squareup.retrofit2:converter-kotlinx-serialization", version.ref = "square-retrofit2" }
cash-sqlDelightAndroidDriver = { module = "app.cash.sqldelight:android-driver", version.ref = "cash-sqlDelight" }
cash-sqlDelightCoroutinesExt = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "cash-sqlDelight" }
cash-sqlDelightSqliteDriver = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "cash-sqlDelight" }

# Gradle plugins
plugin-android = { module = "com.android.tools.build:gradle", version.ref = "plugin-android" }
plugin-androidx-navigationSafeArgs = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "androidx-navigation" }
plugin-dagger-hilt = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "dagger-hilt" }
plugin-google-ksp = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-kotlin-compose = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
plugin-kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
plugin-kotlinter = { module = "org.jmailen.gradle:kotlinter-gradle", version.ref = "plugin-kotlinter" }
plugin-square-sqlDelight = { module = "app.cash.sqldelight:gradle-plugin", version.ref = "cash-sqlDelight" }

[bundles]
square-retrofit2 = ["square-retrofit2", "square-retrofit2ConverterSerialization"]
square-okhttp = ["square-okhttp", "square-okhttpLoggingInterceptor"]

[plugins]
android-application = { id = "com.android.application", version.ref = "plugin-android" }
android-library = { id = "com.android.library", version.ref = "plugin-android" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger-hilt" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "plugin-kotlinter" }
doctor = { id = "com.osacky.doctor", version.ref = "plugin-doctor" }
cash-sqlDelight = { id = "app.cash.sqldelight", version.ref = "cash-sqlDelight" }
